CUDA_VISIBLE_DEVICES=4 python -m torch.distributed.run --nproc_per_node 1 fine-tune-dp.py \
    --output_dir scratch \
    --model_name meta-llama/Llama-3.2-1B \
    --sequence_len 512 \
    --train_file /home/srini/dp-transformers/psytar/train-original.jsonl \
    --per_device_train_batch_size 16 \
    --gradient_accumulation_steps 1 \
    --eval_steps 45 \
    --log_level info \
    --per_device_eval_batch_size 32 \
    --eval_accumulation_steps 1 \
    --seed 42 \
    --prediction_loss_only \
    --weight_decay 0.01 \
    --remove_unused_columns False \
    --num_train_epochs 5 \
    --logging_steps 5 \
    --lora_dim 4 \
    --lora_alpha 32 \
    --lora_dropout 0.0 \
    --max_grad_norm 0 \
    --lr_scheduler_type constant \
    --learning_rate 3e-4 \
    --disable_tqdm True \
    --dataloader_num_workers 2 \
    --label_names labels \
    --lr_scheduler_type cosine \
    --warmup_ratio 0.3 \
    --enable_lora